sudo: required
services:
  - docker

before_install:
  - docker build -t cradle81/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true cradle81/docker-react npm run test -- --coverage
#   - docker run cradle81/docker-react npm run test -- --coverage
